version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  base_image:
    build:
      dockerfile: Dockerfile
    image: my-python-base
 
  user:
    container_name: fastapi_user
    build:
      dockerfile: user/Dockerfile
    ports:
      - "8080:8080"
      
volumes:
  mysql_data: